name: Release notifications

on:
  pull_request:
    branches:
      - main
    paths:
      - .release_notes/**

jobs:
  tg_notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: F2had/pr-telegram-action@v1.0.0
        with:
          bot_token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_TO }}
