name: Scheduled Release

on:
  schedule:
    - cron: '0 11 * * 1'
    - cron: '0 11 * * 4'

jobs:
  scheduled_release:
    uses: taskany-inc/release/.github/workflows/release_pr.yml@main
    secrets: inherit
